# Generated by Django 3.0.5 on 2020-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetion',
            name='midless',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
