# Generated by Django 3.0.5 on 2020-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0002_quetion_midless'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetion',
            name='firstq_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quetion',
            name='lastqs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
