# Generated by Django 3.0.5 on 2020-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0003_auto_20200422_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_id', models.IntegerField()),
                ('heading1', models.CharField(blank=True, max_length=245, null=True)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('heading2', models.CharField(blank=True, max_length=245, null=True)),
                ('description3', models.TextField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('lang_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'about',
                'managed': False,
            },
        ),
    ]
