# Generated by Django 3.0.5 on 2020-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.TextField()),
                ('facebook_id', models.TextField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('date_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('phonecodecountry', models.CharField(max_length=10)),
                ('phonecode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('show_phone', models.IntegerField()),
                ('password', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.CharField(max_length=100)),
                ('profile_image_verified', models.IntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('experience_year', models.IntegerField()),
                ('experience_month', models.IntegerField()),
                ('industry_id', models.IntegerField()),
                ('summary', models.TextField()),
                ('education', models.TextField()),
                ('full_work_type', models.IntegerField()),
                ('part_work_type', models.IntegerField()),
                ('fullpart_work_type', models.IntegerField()),
                ('freelance_work_type', models.IntegerField()),
                ('fixed_price', models.CharField(max_length=50)),
                ('fixed_price_currency', models.IntegerField()),
                ('perhour_price', models.CharField(max_length=50)),
                ('perhour_price_currency', models.IntegerField()),
                ('phoneopt', models.CharField(max_length=50)),
                ('phoneotpstatus', models.IntegerField()),
                ('otpdatetime', models.DateTimeField()),
                ('emailotp', models.CharField(max_length=50)),
                ('emailotpstatus', models.IntegerField()),
                ('emailotpdatetime', models.DateTimeField()),
                ('registration_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField()),
                ('activation_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('work_type', models.CharField(blank=True, max_length=45, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=45, null=True)),
                ('lat', models.CharField(blank=True, max_length=45, null=True)),
                ('long', models.CharField(blank=True, max_length=45, null=True)),
                ('is_live', models.IntegerField(blank=True, null=True)),
                ('show_map', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
