# Generated by Django 3.0.5 on 2020-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ae', models.CharField(blank=True, max_length=200, null=True)),
                ('title_he', models.CharField(blank=True, max_length=250, null=True)),
                ('title_ur', models.CharField(blank=True, max_length=250, null=True)),
                ('title_ch', models.CharField(blank=True, max_length=250, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('title_gr', models.CharField(blank=True, max_length=250, null=True)),
                ('title_sp', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'new_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=250)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
    ]
