# Generated by Django 3.0.5 on 2020-04-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0006_category_newskills_settings_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quetion',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
