# Generated by Django 3.0.5 on 2020-04-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0007_auto_20200423_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='newskills',
            options={'managed': False, 'verbose_name_plural': 'skill'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'managed': False, 'verbose_name_plural': 'setting'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'managed': False, 'verbose_name_plural': 'skill'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'user'},
        ),
    ]
