# Generated by Django 3.0.5 on 2020-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm_app', '0008_auto_20200424_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('emails_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_name', models.CharField(max_length=250)),
                ('from_email', models.CharField(max_length=250)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('email_type', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagePosts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('post_type', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.IntegerField()),
                ('othercategory', models.CharField(max_length=255)),
                ('candidate_jobtype', models.IntegerField()),
                ('description', models.TextField()),
                ('uploaded_file', models.CharField(max_length=255)),
                ('pay_type', models.IntegerField(blank=True, null=True)),
                ('pay_amount', models.IntegerField()),
                ('pay_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('lang_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('expirydate', models.DateField()),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manage_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('contacted_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_contact',
                'managed': False,
            },
        ),
    ]
